export const CONFIG = Object.freeze({
  accountId: '347288884992',
  profile: 'preview',
  region: 'us-west-2',
  domain: 'duranta-preview.com',
  hostedZoneId: 'Z065720819EWCTX1GV9K9',
  subnetId: 'subnet-091fc3de4f16e3ea7',
  securityGroupId: 'sg-05e840ada58c79901',
  instanceProfile: 'duranta-preview-instance',
  architecture: 'arm64',
  workspaceInstanceType: 't4g.2xlarge',
  builderInstanceType: 't4g.2xlarge',
  volumeSize: 100,
  sshUser: 'ubuntu',
  ttl: '48h',
  maxInstancesPerCreator: 10,
  keepAmis: 2,
  baseAmiParameter: '/aws/service/canonical/ubuntu/server/26.04/stable/current/arm64/hvm/ebs-gp3/ami-id',
  goldenAmiParameter: '/duranta-preview/golden-ami-id-arm64',
  managedBy: 'duranta-preview',
});
